version: '3.9'
services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning